[build]
  command = "next build"
  publish = ".next"
  functions = "netlify/functions"

[[redirects]]
  from = "/_next/*"
  to = "/.netlify/functions/next/*"
  status = 200
  force = true

[[plugins]]
  package = "@netlify/plugin-nextjs"